name: "Test"
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [20.09]
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - run: nix run nixpkgs.hlint -c hlint .
    - run: nix-build release.nix -I nixpkgs=channel:nixos-${{ matrix.channel }}
    - run: nix-shell -I nixpkgs=channel:nixos-${{ matrix.channel }} --run ./restyle.sh
    - run: git diff --exit-code
